### ISSUE TITLE
Tracking package registries

### ISSUE THREAD

**Issue by sachaos** [sachaos/viddy#136]
Viddy v1.0.0 have been released.
https://github.com/sachaos/viddy/issues/117

But some package registries may not support v1.0.0 yet.

- [x] Homebrew https://github.com/Homebrew/homebrew-core/pull/181977
- [ ] Nix https://github.com/NixOS/nixpkgs/pull/336100
- [x] MacPorts https://github.com/macports/macports-ports/commit/a31c239d73cd94fe6ae43d98b9c8689b65cda769
- [ ] asdf
- [ ] ArchLinux
- [ ] scoop
- [ ] Alpine Linux

**Comment by Araxeus** [comment]
Consider publishing on Winget, theres even an easy github action https://github.com/vedantmgoyal9/winget-releaser

**Comment by sachaos** [comment]
@xfzv  Thank you.
Viddy is available at crates.io now.
https://crates.io/crates/viddy

**Comment by sachaos** [comment]
@Araxeus Thank you, it seems nice idea.
But, I'm not Windows user, I would appreciate it if someone could help.
I've created another issue.

https://github.com/sachaos/viddy/issues/144
